const W = 400;
const H = 400;
const FOOTER = `Generated by insideinvoice.com \u00b7 \u00a9 ${new Date().getFullYear()}`;

const RED = "#E4002B";
const GREEN = "#00A651";
const BLUE = "#0072BC";
const ORANGE = "#FF6600";
const GOLD = "#FFD700";
const YELLOW = "#FFEB00";
const RYEL = "#FFF200";
const WHITE = "#FFFFFF";
const BLACK = "#000000";

// Mirrors backend HazardClass (49 CFR 172.407 / IATA DGR 7.2).
const CLASSES = {
  "1": { hex: ORANGE, pattern: "solid", name: "EXPLOSIVES", numeral: "1", symbol: "bomb" },
  "2.1": { hex: RED, pattern: "solid", name: "FLAMMABLE GAS", numeral: "2", symbol: "flame" },
  "2.2": { hex: GREEN, pattern: "solid", name: "NON-FLAMMABLE NON-TOXIC GAS", numeral: "2", symbol: "cylinder" },
  "2.3": { hex: WHITE, pattern: "solid", name: "TOXIC GAS", numeral: "2", symbol: "skull" },
  "3": { hex: RED, pattern: "solid", name: "FLAMMABLE LIQUID", numeral: "3", symbol: "flame" },
  "4.1": { hex: WHITE, pattern: "stripesRed7", name: "FLAMMABLE SOLID", numeral: "4", symbol: "flame" },
  "4.2": { hex: WHITE, pattern: "halfRedBottom", name: "SPONTANEOUS COMBUSTIBLE", numeral: "4", symbol: "flame" },
  "4.3": { hex: BLUE, pattern: "solid", name: "DANGEROUS WHEN WET", numeral: "4", symbol: "flame" },
  "5.1": { hex: GOLD, pattern: "solid", name: "OXIDIZER", numeral: "5.1", symbol: "flameCircle" },
  "5.2": { hex: YELLOW, pattern: "halfTopRedYellow", name: "ORGANIC PEROXIDE", numeral: "5.2", symbol: "flame" },
  "6.1": { hex: WHITE, pattern: "solid", name: "TOXIC", numeral: "6", symbol: "skull" },
  "6.2": { hex: WHITE, pattern: "solid", name: "INFECTIOUS SUBSTANCE", numeral: "", symbol: "biohazard" },
  "7": { hex: RYEL, pattern: "halfYellowWhite", name: "RADIOACTIVE", numeral: "", symbol: "trefoil" },
  "8": { hex: WHITE, pattern: "halfBlackBottom", name: "CORROSIVE", numeral: "8", symbol: "corrosive" },
  "9": { hex: WHITE, pattern: "stripesBlack7Upper", name: "MISCELLANEOUS", numeral: "9", symbol: "none" },
  "9A": { hex: WHITE, pattern: "solid", name: "LITHIUM BATTERY", numeral: "9", symbol: "battery" },
};

function resolveClass(key) {
  const k = String(key || "").trim().toUpperCase();
  if (CLASSES[k]) return CLASSES[k];
  switch (k.charAt(0)) {
    case "1": return CLASSES["1"];
    case "2":
      if (k.startsWith("2.2") || k === "22") return CLASSES["2.2"];
      if (k.startsWith("2.3") || k === "23") return CLASSES["2.3"];
      return CLASSES["2.1"];
    case "3": return CLASSES["3"];
    case "4":
      if (k.startsWith("4.2")) return CLASSES["4.2"];
      if (k.startsWith("4.3")) return CLASSES["4.3"];
      return CLASSES["4.1"];
    case "5": return k.startsWith("5.2") ? CLASSES["5.2"] : CLASSES["5.1"];
    case "6": return k.startsWith("6.2") ? CLASSES["6.2"] : CLASSES["6.1"];
    case "7": return CLASSES["7"];
    case "8": return CLASSES["8"];
    default: return CLASSES["9"];
  }
}

function luminance(hex) {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
const inkOn = (bg) => (luminance(bg) > 0.55 ? BLACK : WHITE);

function halves(hc) {
  switch (hc.pattern) {
    case "halfRedBottom": return [WHITE, RED];
    case "halfTopRedYellow": return [RED, YELLOW];
    case "halfYellowWhite": return [RYEL, WHITE];
    case "halfBlackBottom": return [WHITE, BLACK];
    default: return [hc.hex, hc.hex];
  }
}

function symbolArt(kind, ink) {
  const ko = "#fff";
  switch (kind) {
    case "flame":
      return <path d="M50 4 C58 24 76 34 76 56 C76 79 64 96 50 96 C36 96 24 79 24 56 C24 42 34 36 38 24 C42 34 47 38 50 4 Z" fill={ink} />;
    case "cylinder":
      return <g fill={ink}><rect x="28" y="16" width="44" height="78" rx="16" /><rect x="41" y="0" width="18" height="20" rx="5" /></g>;
    case "skull":
      return (
        <g>
          <path d="M50 6 C74 6 90 24 90 46 C90 60 82 70 72 76 L72 88 L28 88 L28 76 C18 70 10 60 10 46 C10 24 26 6 50 6 Z" fill={ink} />
          <circle cx="35" cy="46" r="9" fill={ko} />
          <circle cx="65" cy="46" r="9" fill={ko} />
          <path d="M50 58 L57 72 L43 72 Z" fill={ko} />
          <g stroke={ko} strokeWidth="3">
            <line x1="40" y1="76" x2="40" y2="88" />
            <line x1="50" y1="76" x2="50" y2="88" />
            <line x1="60" y1="76" x2="60" y2="88" />
          </g>
        </g>
      );
    case "bomb":
      return <g fill={ink}><circle cx="45" cy="62" r="34" /><path d="M67 36 C76 22 86 17 95 20" stroke={ink} strokeWidth="7" fill="none" strokeLinecap="round" /></g>;
    case "flameCircle":
      return (
        <g>
          <path d="M50 2 C57 18 70 26 70 44 C70 62 61 74 50 74 C39 74 30 62 30 44 C30 32 38 28 41 18 C45 27 48 30 50 2 Z" fill={ink} />
          <circle cx="50" cy="84" r="13" fill="none" stroke={ink} strokeWidth="7" />
        </g>
      );
    case "biohazard":
      return (
        <g fill={ink}>
          <circle cx="50" cy="50" r="13" />
          <circle cx="50" cy="22" r="17" />
          <circle cx="26" cy="66" r="17" />
          <circle cx="74" cy="66" r="17" />
          <circle cx="50" cy="27" r="6" fill={ko} />
          <circle cx="32" cy="61" r="6" fill={ko} />
          <circle cx="68" cy="61" r="6" fill={ko} />
        </g>
      );
    case "trefoil":
      return (
        <g fill={ink}>
          {[0, 120, 240].map((a) => (
            <path key={a} d="M50 50 L50 3 A47 47 0 0 1 90.7 26.5 Z" transform={`rotate(${a} 50 50)`} />
          ))}
          <circle cx="50" cy="50" r="11" />
        </g>
      );
    case "corrosive":
      return (
        <g fill={ink}>
          <rect x="10" y="4" width="30" height="15" rx="7" transform="rotate(38 25 11)" />
          <rect x="60" y="4" width="30" height="15" rx="7" transform="rotate(-38 75 11)" />
          <circle cx="31" cy="48" r="5" />
          <circle cx="69" cy="48" r="5" />
          <path d="M6 62 L50 62 L50 86 L14 86 Z" />
          <rect x="56" y="66" width="38" height="20" rx="4" />
        </g>
      );
    case "battery":
      return <g fill={ink}><rect x="14" y="26" width="66" height="52" rx="8" /><rect x="80" y="40" width="12" height="24" rx="4" /><rect x="26" y="12" width="20" height="14" rx="4" /></g>;
    default:
      return null;
  }
}

function Footer({ x = 14, y = H - 10, anchor = "start", width = W }) {
  return (
    <text
      x={anchor === "start" ? x : width - x}
      y={y}
      fontSize="10"
      fill="#64748b"
      textAnchor={anchor}
      fontFamily="Inter, Helvetica, Arial, sans-serif"
    >
      {FOOTER}
    </text>
  );
}

function HatchDefs() {
  return (
    <defs>
      <pattern id="haz-hatch" width="12" height="12" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
        <rect width="12" height="12" fill={WHITE} />
        <rect width="6" height="12" fill={RED} />
      </pattern>
    </defs>
  );
}

const hatchBand = 32;

function HatchFrame() {
  return (
    <g>
      <path
        d={`M0 0 H${W} V${H} H0 Z M${hatchBand} ${hatchBand} H${W - hatchBand} V${H - hatchBand} H${hatchBand} Z`}
        fillRule="evenodd"
        fill="url(#haz-hatch)"
      />
      <rect x="1.5" y="1.5" width={W - 3} height={H - 3} fill="none" stroke={BLACK} strokeWidth="3" />
      <rect x={hatchBand} y={hatchBand} width={W - 2 * hatchBand} height={H - 2 * hatchBand} fill="none" stroke={BLACK} strokeWidth="2" />
    </g>
  );
}

function Diamond({ payload, cls }) {
  const cx = W / 2;
  const cy = H / 2;
  const R = Math.min(W, H) / 2 - 4;
  const S = 2 * R;
  const innerR = R - 0.05 * S * Math.SQRT2;
  const [upper, lower] = halves(cls);

  const poly = (r) => `${cx},${cy - r} ${cx + r},${cy} ${cx},${cy + r} ${cx - r},${cy}`;

  const bandW = S / 14;
  const stripes = [];
  for (let k = 0; k < 14; k += 2) stripes.push(cx - R + k * bandW);

  const numeral =
    cls.numeral === "1"
      ? `${payload.division || ""}${payload.compatGroup || ""}`.trim() || cls.numeral
      : cls.numeral;
  const middle = cls.name;
  const subs = String(payload.subsidiaryRisks || "").trim();

  const upperInk = inkOn(upper);
  const lowerInk = inkOn(lower);

  return (
    <g>
      <defs>
        <clipPath id="haz-dia"><polygon points={poly(R)} /></clipPath>
        <clipPath id="haz-upper"><rect x="0" y={cy - R - 4} width={W} height={R + 4} /></clipPath>
      </defs>

      <rect width={W} height={H} fill={WHITE} />
      <g clipPath="url(#haz-dia)">
        {cls.pattern === "stripesRed7" &&
          stripes.map((x) => <rect key={x} x={x} y={cy - R} width={bandW} height={S} fill={RED} />)}
        {cls.pattern === "stripesBlack7Upper" && (
          <g clipPath="url(#haz-upper)">
            {stripes.map((x) => <rect key={x} x={x} y={cy - R} width={bandW} height={S} fill={BLACK} />)}
          </g>
        )}
        {cls.pattern.startsWith("half") && (
          <>
            <rect x={cx - R} y={cy - R} width={S} height={R} fill={upper} />
            <rect x={cx - R} y={cy} width={S} height={R} fill={lower} />
          </>
        )}
        {cls.pattern === "solid" && <rect x={cx - R} y={cy - R} width={S} height={S} fill={cls.hex} />}
      </g>

      <polygon points={poly(R)} fill="none" stroke={BLACK} strokeWidth="4" />
      <polygon points={poly(innerR)} fill="none" stroke={BLACK} strokeWidth="3" />

      {cls.symbol !== "none" && (
        <g transform={`translate(${cx - 0.15 * S} ${cy - 0.5 * S}) scale(${(0.3 * S) / 100})`}>
          {symbolArt(cls.symbol, upperInk)}
        </g>
      )}

      <text
        x={cx}
        y={cy + 0.055 * S + 8}
        fontSize={Math.min(26, (0.05 * S) / 0.72)}
        fontWeight="700"
        fill={lowerInk}
        textAnchor="middle"
        fontFamily="Inter, Helvetica, Arial, sans-serif"
      >
        {middle.length > 42 ? middle.slice(0, 39) + "..." : middle}
      </text>

      <text
        x={cx}
        y={cy + 0.215 * S + 20}
        fontSize={(0.127 * S) / 0.72}
        fontWeight="700"
        fill={lowerInk}
        textAnchor="middle"
        fontFamily="Inter, Helvetica, Arial, sans-serif"
      >
        {numeral}
      </text>
      {numeral.startsWith("9") && (
        <rect x={cx - 22} y={cy + 0.215 * S + 26} width={44} height={3} fill={lowerInk} />
      )}
      {subs && (
        <text
          x={cx}
          y={cy + 0.215 * S + 46}
          fontSize="14"
          fill={lowerInk}
          textAnchor="middle"
          fontFamily="Inter, Helvetica, Arial, sans-serif"
        >
          SUB: {subs}
        </text>
      )}

      {cls.symbol === "trefoil" && payload.radiationCategory && (
        <g>
          {["I", "II", "III"].map((cat, i) => (
            <g key={cat} transform={`translate(${cx + 62} ${cy - 96 + i * 34})`}>
              <rect width="32" height="30" fill={WHITE} stroke={BLACK} strokeWidth="2.5" />
              <text x="16" y="21" fontSize="15" fontWeight="700" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
                {cat}
              </text>
            </g>
          ))}
        </g>
      )}

      <Footer />
    </g>
  );
}

function Lithium({ payload }) {
  const phone = String(payload.emergencyPhone || "").trim();
  const un = String(payload.unNumber || "UN3480").toUpperCase();
  const body = "#111111";
  const cluster = (
    <g transform={`translate(${W / 2 - 150} 52)`}>
      <g transform="translate(0 8)">
        <path d="M24 0 C31 14 44 22 44 40 C44 58 35 70 24 70 C13 70 4 58 4 40 C4 28 12 24 15 14 C19 23 22 26 24 0 Z" fill={body} />
      </g>
      <rect x="52" y="6" width="30" height="104" rx="15" fill={body} />
      <rect x="60" y="-4" width="14" height="12" rx="3" fill={WHITE} stroke={body} strokeWidth="2.5" />
      <rect x="88" y="6" width="30" height="104" rx="15" fill={body} />
      <rect x="96" y="-4" width="14" height="12" rx="3" fill={WHITE} stroke={body} strokeWidth="2.5" />
      <rect x="126" y="0" width="46" height="112" rx="23" fill={body} />
      <rect x="136" y="-10" width="26" height="14" rx="4" fill={WHITE} stroke={body} strokeWidth="3" />
      <polygon points="156 18 138 62 150 62 142 96 172 50 158 50 168 18" fill={WHITE} />
      <rect x="184" y="6" width="66" height="46" rx="6" fill={body} />
      <rect x="196" y="-6" width="12" height="12" rx="3" fill={WHITE} stroke={body} strokeWidth="2.5" />
      <rect x="214" y="-6" width="12" height="12" rx="3" fill={WHITE} stroke={body} strokeWidth="2.5" />
      <rect x="184" y="64" width="84" height="42" rx="8" fill={body} />
      <rect x="264" y="76" width="14" height="18" rx="3" fill={WHITE} stroke={body} strokeWidth="2.5" />
    </g>
  );

  return (
    <g>
      <HatchDefs />
      <rect width={W} height={H} fill={WHITE} />
      <HatchFrame />
      {cluster}
      <text x={W / 2} y={H * 0.56} fontSize="56" fontWeight="800" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        {un}
      </text>
      <text x={W / 2} y={H * 0.73} fontSize="17" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        {phone ? `For more information, call: ${phone}` : "For more information, call: the shipper"}
      </text>
      {payload.lithiumPackingInstruction && (
        <text x={W / 2} y={H * 0.86} fontSize="14" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
          IATA PI {payload.lithiumPackingInstruction}
        </text>
      )}
      <Footer x={hatchBand + 8} y={H - hatchBand - 14} />
    </g>
  );
}

function Excepted({ payload }) {
  const mark = String(payload.hazardClass || "*").trim().toUpperCase();
  const consignor = String(payload.consignor?.company || payload.consignor?.name || "").trim();
  return (
    <g>
      <HatchDefs />
      <rect width={W} height={H} fill={WHITE} />
      <HatchFrame />
      <text x={W / 2} y={H * 0.34} fontSize="96" fontWeight="800" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        {mark}
      </text>
      <text x={W / 2} y={H * 0.56} fontSize="34" fontWeight="800" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        EXCEPTED QUANTITY
      </text>
      {consignor && (
        <text x={W / 2} y={H * 0.67} fontSize="20" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
          {consignor.toUpperCase()}
        </text>
      )}
      <Footer x={hatchBand + 8} y={H - hatchBand - 14} />
    </g>
  );
}

function EnvHazard({ payload }) {
  const psn = String(payload.properShippingName || "").trim().toUpperCase();
  return (
    <g>
      <rect width={W} height={H} fill={WHITE} />
      <rect x="2" y="2" width={W - 4} height={H - 4} fill="none" stroke={BLACK} strokeWidth="3" />
      <g transform={`translate(${W / 2 - 130} ${H * 0.12}) scale(2.6)`}>
        <path d="M6 40 C24 18 62 18 84 40 C62 62 24 62 6 40 Z" fill={BLACK} />
        <path d="M84 40 L104 24 L104 56 Z" fill={BLACK} />
        <circle cx="30" cy="36" r="5" fill={WHITE} />
        <path d="M150 96 L150 60 L134 60 L150 24 L166 60 L150 60 L150 96 Z" fill={BLACK} />
        <rect x="146" y="96" width="8" height="10" fill={BLACK} />
        <path d="M118 60 C118 38 140 30 150 30 C160 30 182 38 182 60 C182 78 166 92 150 92 C134 92 118 78 118 60 Z" fill={BLACK} />
      </g>
      <text x={W / 2} y={H * 0.74} fontSize="20" fontWeight="800" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        ENVIRONMENTALLY HAZARDOUS SUBSTANCE
      </text>
      {psn && (
        <text x={W / 2} y={H * 0.81} fontSize="15" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
          {psn}
        </text>
      )}
      <Footer y={H - 14} />
    </g>
  );
}

function Orientation() {
  const color = RED;
  const arrow = (x, y, w, h) => {
    const headH = h * 0.34;
    const shaft = w * 0.42;
    return (
      <polygon
        key={x}
        points={`${x + w / 2},${y} ${x + w},${y + headH} ${x + w / 2 + shaft / 2},${y + headH} ${x + w / 2 + shaft / 2},${y + h} ${x + w / 2 - shaft / 2},${y + h} ${x + w / 2 - shaft / 2},${y + headH} ${x},${y + headH}`}
        fill={color}
      />
    );
  };
  const arrowW = W * 0.3;
  const gap = W * 0.08;
  const total = 2 * arrowW + gap;
  const x0 = (W - total) / 2;
  const top = H * 0.14;
  const arrowH = H * 0.5;
  return (
    <g>
      <rect width={W} height={H} fill={WHITE} />
      <rect x="2" y="2" width={W - 4} height={H - 4} fill="none" stroke={BLACK} strokeWidth="3" />
      {arrow(x0, top, arrowW, arrowH)}
      {arrow(x0 + arrowW + gap, top, arrowW, arrowH)}
      <text x={W / 2} y={top + arrowH + H * 0.06} fontSize="34" fontWeight="800" fill={color} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        THIS WAY UP
      </text>
      <Footer y={H - 14} />
    </g>
  );
}

function Cao({ payload }) {
  const un = String(payload.unNumber || "").trim().toUpperCase();
  return (
    <g>
      <rect width={W} height={H} fill={ORANGE} />
      <rect x="4" y="4" width={W - 8} height={H - 8} fill="none" stroke={BLACK} strokeWidth="4" />
      <text x={W / 2} y={H * 0.17} fontSize="34" fontWeight="800" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        CARGO AIRCRAFT ONLY
      </text>
      <g transform={`translate(${W / 2 - 52} ${H * 0.3})`}>
        <polygon points="52,0 104,44 73,44 73,120 31,120 31,44 0,44" fill={BLACK} />
      </g>
      <text x={W / 2} y={H * 0.72} fontSize="24" fontWeight="800" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        INVALID FOR PASSENGER AIRCRAFT
      </text>
      {un && (
        <text x={W / 2} y={H * 0.84} fontSize="22" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
          {un}
        </text>
      )}
      <Footer y={H - 14} />
    </g>
  );
}

function Overpack({ payload }) {
  const un = String(payload.unNumber || "").trim().toUpperCase();
  return (
    <g>
      <rect width={W} height={H} fill={WHITE} />
      <rect x="6" y="6" width={W - 12} height={H - 12} fill="none" stroke={BLACK} strokeWidth="4" />
      <text x={W / 2} y={H * 0.52} fontSize="76" fontWeight="800" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        OVERPACK
      </text>
      {un && (
        <text x={W / 2} y={H * 0.72} fontSize="22" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
          {un}
        </text>
      )}
      <Footer y={H - 14} />
    </g>
  );
}

function LimitedQuantity({ payload }) {
  const cx = W / 2;
  const cy = H / 2;
  const R = Math.min(W, H) / 2 - 4;
  const S = 2 * R;
  const poly = `${cx},${cy - R} ${cx + R},${cy} ${cx},${cy + R} ${cx - R},${cy}`;
  const code = String(payload.limitedQuantityCode || "").trim().toUpperCase() ||
    (payload.transportMode === "AIR" ? "Y" : "");
  return (
    <g>
      <rect width={W} height={H} fill={WHITE} />
      <polygon points={poly} fill={WHITE} />
      <polygon
        points={`${cx},${cy - R} ${cx - S * 0.25},${cy - S * 0.25} ${cx + S * 0.25},${cy - S * 0.25}`}
        fill={BLACK}
      />
      <polygon
        points={`${cx},${cy + R} ${cx - S * 0.25},${cy + S * 0.25} ${cx + S * 0.25},${cy + S * 0.25}`}
        fill={BLACK}
      />
      <polygon points={poly} fill="none" stroke={BLACK} strokeWidth="4" />
      {code && (
        <text x={cx} y={cy + S * 0.05} fontSize={(0.14 * S) / 0.72} fontWeight="800" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
          {code}
        </text>
      )}
      <text x={cx} y={cy + S * 0.42} fontSize="18" fontWeight="800" fill={BLACK} textAnchor="middle" fontFamily="Inter, Helvetica, Arial, sans-serif">
        LIMITED QUANTITY
      </text>
      <Footer y={H - 14} />
    </g>
  );
}

export default function HazmatLabelPreview({ payload }) {
  const type = payload?.labelType || "CLASS_DIAMOND";
  const cls = resolveClass(payload?.hazardClass);

  let body;
  if (type === "LITHIUM") body = <Lithium payload={payload} />;
  else if (type === "EXCEPTED_QTY") body = <Excepted payload={payload} />;
  else if (type === "ENV_HAZARD") body = <EnvHazard payload={payload} />;
  else if (type === "ORIENTATION") body = <Orientation />;
  else if (type === "CAO") body = <Cao payload={payload} />;
  else if (type === "OVERPACK") body = <Overpack payload={payload} />;
  else if (type === "LIMITED_QTY") body = <LimitedQuantity payload={payload} />;
  else body = <Diamond payload={payload || {}} cls={cls} />;

  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      className="w-full max-w-md mx-auto block rounded-lg border border-slate-200 bg-white"
      role="img"
      aria-label="Hazmat label preview"
    >
      <rect width={W} height={H} fill={WHITE} />
      {body}
    </svg>
  );
}
